resolve install error
ERROR:  While executing gem ... (Gem::DependencyError)
    Unable to resolve dependencies: fluent-plugin-msgpack-rpc requires fluent (~> 0.10.0)